# Generated by Django 6.0.6 on 2026-07-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicstaff',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Monday-Friday 8AM-5PM', 'Monday-Friday 8AM-5PM'), ('Monday-Friday 9AM-6PM', 'Monday-Friday 9AM-6PM'), ('Monday-Saturday 8AM-5PM', 'Monday-Saturday 8AM-5PM'), ('Monday-Saturday 9AM-6PM', 'Monday-Saturday 9AM-6PM'), ('Half Day Morning', 'Half Day Morning'), ('Half Day Afternoon', 'Half Day Afternoon'), ('Flexible Schedule', 'Flexible Schedule')], max_length=255),
        ),
    ]
