# Generated by Django 6.0.6 on 2026-07-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('staff', 'Clinic Staff'), ('doctor', 'Doctor')], default='staff', max_length=20),
        ),
    ]
