# Generated by Django 6.0.6 on 2026-07-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_middle_initial_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('staff', 'Clinic Staff'), ('doctor', 'Doctor'), ('admin', 'Administrator')], default='staff', max_length=20),
        ),
    ]
