# Generated by Django 6.0.6 on 2026-07-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-consultation_date']},
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='medical_notes',
            new_name='consultation_notes',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='prescription',
            new_name='prescribed_medications',
        ),
    ]
