# Generated by Django 6.0.6 on 2026-07-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
