# Generated by Django 6.0.6 on 2026-07-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
