# Generated by Django 6.0.6 on 2026-07-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Off Duty', 'Off Duty')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Family Medicine', 'Family Medicine'), ('Internal Medicine', 'Internal Medicine'), ('Pediatrics', 'Pediatrics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Ophthalmology', 'Ophthalmology'), ('ENT', 'Ear, Nose and Throat (ENT)'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('Anesthesiology', 'Anesthesiology'), ('Emergency Medicine', 'Emergency Medicine'), ('Other', 'Other')], max_length=100),
        ),
    ]
